### DISCUSSION TITLE
How to query a subgraph created on the Subgraph Studio?

### DISCUSSION THREAD

**Discussion by ubinatus** [graphprotocol/graph-client#536] [Q&A] [answered]
Hi 👋

This part of the READme is helpful for passing on api keys https://github.com/graphprotocol/graph-client#customize-network-calls

``` yml
sources:
  - name: uniswapv2
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v2
        operationHeaders:
          Authorization: Bearer {context.config.apiToken}
````

However, querying the Subgraph Studio requires the ApiKey to be on the endpoint url per se (e.g. `https://gateway.thegraph.com/api/API_KEY/subgraphs/id/some_somgraph_id`).

Mind explaining if this can be achieved using `@graphprotocol/graph-client`? If so, how can we handle subgraph studio queries? 

Thank you!

**Comment by ardatan** [comment, marked as answer]
You can use the same interpolation logic for `endpoint` BUT keep on mind it still needs to introspect the schema first. So I'd recommend to use environment variables for this;

```yml
sources:
  - name: uniswapv2
    handler:
      graphql:
        endpoint: https://gateway.thegraph.com/api/{env.API_KEY}/subgraphs/id/some_somgraph_id
```

**Reply by ubinatus** [reply]
Hi @ardatan Thanks for your response! <3

Since we have different api keys for different subgraph with the same underlying schema, ended up doing something like this by using a context:

```yml
sources:
  - name: Foo
    handler:
      graphql:
        endpoint: https://gateway.thegraph.com/api/{context.subgraphApiKey:default_api_key}/subgraphs/id/{context.subgraphId:default_subgraph_id}
```

In which `default_api_key` could be rotated after each introspection.

Main purpose is to be able to pass the api key and subgraph id in runtime but also be able to introspect the subgraph at build, by passing a default set. This is because we use the same subgraph schema for different chains. So we may want to do the following:

```typescript
import { getBuiltGraphSDK } from "./.graphclient";

const sdk = getBuiltGraphSDK();

// Query for ethereum mainnet
const { bar } = await sdk.BarQuery(variables, {
  subgraphId: env.SUBGRAPH_MAINNET_NAME,
  subgraphApiKey: env.SUBGRAPH_MAINNET_KEY
});
// Query for polygon mainnet
const { bar } = await sdk.BarQuery(variables, {
  subgraphId: env.SUBGRAPH_POLYGON_NAME,
  subgraphApiKey: env.SUBGRAPH_POLYGON_KEY
});
```
