### ISSUE TITLE
`pollingLive` not working with `autoTypeMerging`

### ISSUE THREAD

**Issue by hangleang** [graphprotocol/graph-client#394]
Hey, I think I found an issue with `@live queries` feature. When adding a `pollingLive` plugin in `.graphclient.yml` on `composition` example, it stops working and errors out with the following:

```
/home/hangleang/Documents/projects/subgraph/graph-client/node_modules/graphql/validation/validate.js:135
    throw new Error(errors.map((error) => error.message).join('\n\n'));
          ^
Error: Unknown directive "@merge".

Unknown directive "@merge".

Unknown directive "@merge".

Unknown directive "@merge".

Unknown directive "@merge".

Unknown directive "@merge".

Unknown directive "@merge".

Unknown directive "@merge".

Unknown directive "@merge".

Unknown directive "@merge".

Unknown directive "@merge".

Unknown directive "@merge".

Unknown directive "@merge".

Unknown directive "@merge".

Unknown directive "@merge".

Unknown directive "@merge".

Unknown directive "@merge".

Unknown directive "@merge".

Unknown directive "@merge".

Unknown directive "@merge".

Unknown directive "@merge".
    at assertValidSDL (/home/hangleang/Documents/projects/subgraph/graph-client/node_modules/graphql/validation/validate.js:135:11)
    at buildASTSchema (/home/hangleang/Documents/projects/subgraph/graph-client/node_modules/graphql/utilities/buildASTSchema.js:44:34)
    at makeExecutableSchema (/home/hangleang/Documents/projects/subgraph/graph-client/node_modules/@graphql-tools/schema/cjs/makeExecutableSchema.js:73:47)
    at mergeSchemas (/home/hangleang/Documents/projects/subgraph/graph-client/node_modules/@graphql-tools/schema/cjs/merge-schemas.js:32:63)
    at Object.onSchemaChange (/home/hangleang/Documents/projects/subgraph/graph-client/packages/polling-live/dist/cjs/index.js:11:57)
    at createEnvelopOrchestrator (/home/hangleang/Documents/projects/subgraph/graph-client/node_modules/@envelop/core/cjs/orchestrator.js:430:24)
    at envelop (/home/hangleang/Documents/projects/subgraph/graph-client/node_modules/@envelop/core/cjs/create.js:10:74)
    at new YogaServer (/home/hangleang/Documents/projects/subgraph/graph-client/node_modules/graphql-yoga/cjs/server.js:203:48)
    at createYoga (/home/hangleang/Documents/projects/subgraph/graph-client/node_modules/graphql-yoga/cjs/server.js:357:20)
    at /home/hangleang/Documents/projects/subgraph/graph-client/node_modules/@graphql-mesh/http/cjs/graphqlHandler.js:9:79
error Command failed with exit code 1.
```

**Comment by hangleang** [comment]
`.graphclientrc.yml`

```
sources:
  - name: nft
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/amxx/eip721-subgraph
    transforms:
      # Rename Account to User to apply Type Merging
      - rename:
          - from:
              type: Account
            to:
              type: User
      - autoTypeMerging: true

  - name: uniswap
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v2
    transforms:
      - autoTypeMerging: true

plugins:
  - pollingLive:
      defaultInterval: 1000

```
