### ISSUE TITLE
Support Subgraphs deployed in cross-chain mode  

### ISSUE THREAD

**Issue by dotansimha** [graphprotocol/graph-client#41]
Based on our talk and discussions with multiple users, we saw a need to support identical Subgraphs that are deployed on different chains. 

This issue tries to cover the needs, use-cases, and requirements to support this feature as part of the client-side composition feature.

### Use-case 1: Subgraphs are managed separately and prefixed 

Status: ✅ (can be implemented now without any changes to `graph-client`)

```mermaid
flowchart TB
    linkStyle default interpolate basis
    c1[(Chain 1)]-->t1
    c2[(Chain 2)]-->t2

    subgraph "Subgraph A"
    t1("type Something")
    end

    subgraph "Subgraph B"
    t2("type Something")
    end

    t1---ccc
    t2---ccc
    ccc["Client-side composition"]---gc["Graph Client"]

    subgraph m["Composed Schema"]
    t3("type A_Something")
    t4("type B_Something")
    t5("type Query {\na_something: [A_Something!]!\nb_something: [B_Something!]! \n}")

    end

    gc---m
``` 

In such a scenario, developers might want to use multiple Subgraphs that have the same definition but might run on different chains. The fact that both are running under the same Subgraph definition will lead to a conflict due to the fact that both schemas have the same `type X` (even if the schemas/typedefs are the same). 

In this case, a developer might want to prefix each schema types while being compose, at the level of each source:

```yml
sources:
  - name: subgraphA
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/test/a
    transforms:
      - prefix:
          value: A_
          includeRootOperations: true
          ignore:
            - _SubgraphErrorPolicy_
  - name: subgraphB
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/test/b
    transforms:
      - prefix:
          value: B_
          includeRootOperations: true
          ignore:
            - _SubgraphErrorPolicy_
```

This way, the merged schema can allow users to execute one query, but orchestrate the call through multiple chains: 

```graphql
query something($t: String) { # you can even pass the same GraphQL variable, into multiple GraphQL field arguments
   A_something(t: $t) {
     id
   }
   B_something(t: $t) {
     id
   }
}
```

### Use-case 2: Merge responses

Status: ❓ 

```mermaid
flowchart TB
    linkStyle default interpolate basis
    c1[(Chain 1)]-->t1
    c2[(Chain 2)]-->t2

    subgraph "Subgraph A"
    t1("type Something")
    end

    subgraph "Subgraph B"
    t2("type Something")
    end

    t1---ccc
    t2---ccc
    ccc["Client-side composition"]---gc["Graph Client"]

    subgraph m["Composed Schema"]
    t3("type Something")
    t4("type Query {\n something: [Something!]! \n}")
    end

    gc---m
``` 

In such a scenario, the user doesn't care which Subgraph originates which data, and the data is just being merged together, this could be useful for fetching lists of objects cross-chains. 

```graphql
query something($t: String) {
   something(t: $t) { # this will return a list of Something, originated on both A and B Subgraphs
     id
   }
}
```

> Side-note: this might break pagination since you might do: `{ first: 10 }` on the query level, but actually get `20` records. 

> Side-note: this might break sorting. 

### Use-case 3: Merge root-operation, while `union` the responses

Status: ❓ 

```mermaid
flowchart TB
    linkStyle default interpolate basis
    c1[(Chain 1)]-->t1
    c2[(Chain 2)]-->t2

    subgraph "Subgraph A"
    t1("type Something")
    end

    subgraph "Subgraph B"
    t2("type Something")
    end

    t1---ccc
    t2---ccc
    ccc["Client-side composition"]---gc["Graph Client"]

    subgraph m["Composed Schema"]
    t3("type A_Something")
    t4("type B_Something")
    t5("union Something = A_Something | B_Something")
    t6("type Query {\n something: [Something!]! \n}")
    end

    gc---m
``` 

Similar to use-case number 2, but in this case the user might want to be able to distinguish where the record came from (origin of the Subgraph). In this case, we can create a GraphQL `union` that points to both types, and then user can do at query level: 

```graphql
query something($t: String) {
   something(t: $t) { # this will return a list of Something, originated on both A and B Subgraphs
      __typename # will be A_Something or B_Something  
     ... on A_Something {
       id
     } 
     ... on B_Something {
       id
     } 
   }
}
```

Or, actually, if we are using GraphQL `interface`, it can be: 

```graphql
query something($t: String) {
   something(t: $t) { # this will return a list of Something, originated on both A and B Subgraphs
      __typename # will be A_Something or B_Something  
       id
   }
}
```
