### ISSUE TITLE
build time environment variables not working

### ISSUE THREAD

**Issue by gigamesh** [graphprotocol/graph-client#643]
If I follow the instructions in the readme and specify an env var like this in .graphclientrc.yml:

```
sources:
  - name: farther
    handler:
      graphql:
        endpoint: https://api.studio.thegraph.com/query/{env.SUBGRAPH}/version/latest
```
and then start the process with the following script: `SUBGRAPH=<subgraph-id> graphclient build`

...the variable doesn't get injected. Does anyone know why?
